version: '3.4'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G
    restart: always
    links:
      - backend
    ports:
      - 80:80
    networks:
      - casaferreteranet
  backend:
    build:
      context: ./backend
    container_name: backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G
    restart: always
    ports:
      - 8081:8081
    networks:
      - casaferreteranet
networks:
  casaferreteranet:
    driver: bridge