name: Deploy CasaFerretera to GCP with Docker - staging

on:
  push:
    branches:
      - main

jobs:
    build-and-publish:
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build fastAPI and publish to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: backend
            push: true
            tags: julianv08/casaferreterabackend:latest, julianv08/casaferreterabackend:${{ github.run_number }}
        - name: Build ReactJs and publish to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: frontend
            push: true
            tags: julianv08/casaferreterafrontend:latest, julianv08/casaferreterafrontend:${{ github.run_number }}

    deploy:
      needs: build-and-publish
      runs-on: ubuntu-latest
      steps:
        - name: Set up gcloud CLI
          uses: google-github-actions/setup-gcloud@v0.3.0
          with:
            project_id: ${{ secrets.GCE_PROJECT_ID }}
            service_account_key: ${{ secrets.GCE_SA_KEY }}
            export_default_credentials: true

        - name: Access gcloud CLI
          run: |
            gcloud auth configure-docker

        - name: Checkout repository
          uses: actions/checkout@v3

        - name: scp into GCP instance
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.GCE_INSTANCE_IP_STAGING }}
            username: ${{ secrets.GCE_SSH_USERNAME }}
            key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
            source: "docker-compose.yaml"
            target: "/home/${{ secrets.GCE_SSH_USERNAME }}/"

        - name: SSH into GCP instance and deploy CasaFerretera
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.GCE_INSTANCE_IP_STAGING }}
            username: ${{ secrets.GCE_SSH_USERNAME }}
            key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
            script: |
              sudo docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yaml --profile staging down
              sudo docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yaml --profile staging build --pull
              sudo docker compose -f /home/${{ secrets.GCE_SSH_USERNAME }}/docker-compose.yaml --profile staging up -d

              sudo docker image prune -f